version: '3'
services:
  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "5000:5000"

  telegram_bot:
    build:
      context: ./bot
    container_name: telegram_bot
    environment:
      - TELEGRAM_TOKEN=8071926281:AAFus4IZclSClhaQ9cWh6J9vv8U1W6FpRdQ  # Укажите токен для бота
    depends_on:
      - api
