services:
  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "8000:8000"

  telegram_bot:
    build:
      context: ./bot
    container_name: telegram_bot
    environment:
      - TELEGRAM_TOKEN=8071926281:AAFVPw87DZaYgHmit3ODWpW543PnPrR9jFA
    depends_on:
      - api

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
